In [7]:
from transformer_lens.model_bridge import TransformerBridge
import os
from dotenv import load_dotenv
load_dotenv()
# HF_KEY = os.getenv("HF_KEY")

# Method 1: Simple loading (recommended)
bridge = TransformerBridge.boot_transformers(
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B",
    # token=HF_KEY,
    device="cpu",  # or "cpu"
    # dtype="float32",
    trust_remote_code=False,  # Usually not needed for official models
)

# Test basic forward pass
# text = "Hello, how are you?"
# logits = bridge(text, return_type="logits")
# print(f"Logits shape: {logits.shape}")

# Test text generation
generated = bridge.generate("Once upon a time", max_new_tokens=50)
print(f"Generated text: {generated}")

# # Test run_with_cache (for mechanistic interpretability)
# logits, cache = bridge.run_with_cache("The meaning of life is")
# print(f"Cache keys: {cache.keys()}")

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

100%|██████████| 50/50 [00:21<00:00,  2.31it/s]

Generated text: Once upon a time, there were three kingdoms: West Kingdom, North Kingdom, and East Kingdom.

Each kingdom had its own culture and leadership structure. West Kingdom had a single king, who because of his militaristic background, had his likes turned into his dislikes. The

In [24]:
import os
import json
from pathlib import Path
from collections import Counter
import pandas as pd
base_soln_dir = r"C:\Users\Preet Lodaya\Thought_Anchors\thought-anchors\math_rollouts\accounts\pdlodaya-l7vcn0oxxgj\deployments\dmmz204v\temperature_0.6_top_p_0.95\correct_base_solution"

# Collect all is_correct values
results_df = pd.DataFrame()
row_dict = {}
# Iterate through all subdirectories
for folder in os.listdir(base_soln_dir):
    # print(folder)
    folder_path = os.path.join(base_soln_dir, folder)
    
    # Check if it's a directory
    if os.path.isdir(folder_path):
        base_solution_file = os.path.join(folder_path, "base_solution.json")
        problem_file = os.path.join(folder_path, "problem.json")
        # Check if base_solution.json exists
        if os.path.exists(base_solution_file):
            try:
                with open(base_solution_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    
                row_dict['is_correct'] = data['is_correct']
                row_dict['model_answer'] = data['answer']
                row_dict['full_cot'] = data['full_cot']
            except Exception as e:
                print(f"Error reading {base_solution_file}: {e}")
        if os.path.exists(base_solution_file):
            with open(problem_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
            row_dict['level'] = data['level']
            row_dict['type'] = data['type']
            row_dict['correct_answer'] = data['gt_answer']
            row_dict['problem_id'] = folder_path.split("\\")[-1]
        results_df = pd.concat([results_df, pd.DataFrame([row_dict])], ignore_index=True)
# Count the values
print(results_df['is_correct'].value_counts())

is_correct
True     380
False     43
Name: count, dtype: int64

In [25]:
results_df.groupby('level')['is_correct'].value_counts()

level    is_correct
Level 1  True           57
         False           2
Level 2  True          195
         False          21
Level 3  True           39
         False          11
Level 4  True           44
         False           3
Level 5  True           45
         False           6
Name: count, dtype: int64

In [30]:
results_df.groupby('type')['is_correct'].value_counts()

type                    is_correct
Algebra                 True          104
                        False          12
Counting & Probability  True           31
                        False           3
Geometry                True           34
                        False           8
Intermediate Algebra    True           50
                        False          10
Number Theory           True           38
                        False           2
Prealgebra              True           76
                        False           4
Precalculus             True           47
                        False           4
Name: count, dtype: int64

In [28]:
results_df.loc[results_df['is_correct'] == False].sort_values('level')

,is_correct,model_answer,full_cot,level,type,correct_answer,problem_id
191,False,32768,Solve this math problem step by step. You MUST...,Level 1,Intermediate Algebra,32,problem_4403
231,False,1,Solve this math problem step by step. You MUST...,Level 1,Number Theory,3,problem_5056
54,False,425,Solve this math problem step by step. You MUST...,Level 2,Algebra,\$425,problem_1658
55,False,425,Solve this math problem step by step. You MUST...,Level 2,Algebra,\$425,problem_1658
56,False,"(-2,\ 3)",Solve this math problem step by step. You MUST...,Level 2,Algebra,"(-2,3)",problem_1677
57,False,"(-2,\ 3)",Solve this math problem step by step. You MUST...,Level 2,Algebra,"(-2,3)",problem_1677
97,False,9,Solve this math problem step by step. You MUST...,Level 2,Geometry,36,problem_2536
110,False,55,Solve this math problem step by step. You MUST...,Level 2,Geometry,55^\circ,problem_2718
118,False,"256\,\pi\ \text{cubic feet}",Solve this math problem step by step. You MUST...,Level 2,Geometry,256\pi,problem_2808
142,False,0.3,Solve this math problem step by step. You MUST...,Level 2,Algebra,.3,problem_342
155,False,-5,Solve this math problem step by step. You MUST...,Level 2,Intermediate Algebra,\phantom{09},problem_3563
183,False,,Solve this math problem step by step. You MUST...,Level 2,Intermediate Algebra,1,problem_4265
185,False,,Solve this math problem step by step. You MUST...,Level 2,Algebra,6,problem_428
299,False,\$70,Solve this math problem step by step. You MUST...,Level 2,Prealgebra,70,problem_6228
306,False,50,Solve this math problem step by step. You MUST...,Level 2,Prealgebra,35^\circ,problem_6317
323,False,60,Solve this math problem step by step. You MUST...,Level 2,Prealgebra,50,problem_6524
333,False,240\ \text{miles},Solve this math problem step by step. You MUST...,Level 2,Prealgebra,240,problem_6623
389,False,"(4\sqrt{3}, \frac{\pi}{6})",Solve this math problem step by step. You MUST...,Level 2,Precalculus,"\left( 4 \sqrt{3}, \frac{\pi}{6} \right)",problem_7302
394,False,C,Solve this math problem step by step. You MUST...,Level 2,Precalculus,\text{(C)},problem_7371
405,False,"(2,\ -1)",Solve this math problem step by step. You MUST...,Level 2,Algebra,"(2,-1)",problem_754
406,False,16 \text{ pounds},Solve this math problem step by step. You MUST...,Level 2,Algebra,16,problem_755
420,False,2,Solve this math problem step by step. You MUST...,Level 2,Algebra,x = 2,problem_94
421,False,2,Solve this math problem step by step. You MUST...,Level 2,Algebra,x = 2,problem_94
95,False,96,Solve this math problem step by step. You MUST...,Level 3,Geometry,100,problem_2521
96,False,96,Solve this math problem step by step. You MUST...,Level 3,Geometry,100,problem_2521
111,False,10,Solve this math problem step by step. You MUST...,Level 3,Geometry,10\sqrt{3},problem_2721
112,False,10,Solve this math problem step by step. You MUST...,Level 3,Geometry,10\sqrt{3},problem_2721
113,False,10,Solve this math problem step by step. You MUST...,Level 3,Geometry,10\sqrt{3},problem_2721
157,False,4,Solve this math problem step by step. You MUST...,Level 3,Intermediate Algebra,"4, 6",problem_3623
158,False,4,Solve this math problem step by step. You MUST...,Level 3,Intermediate Algebra,"4, 6",problem_3623
159,False,4,Solve this math problem step by step. You MUST...,Level 3,Intermediate Algebra,"4, 6",problem_3623
167,False,A,Solve this math problem step by step. You MUST...,Level 3,Intermediate Algebra,\text{(A)},problem_3832
177,False,,Solve this math problem step by step. You MUST...,Level 3,Intermediate Algebra,x^4-6x^3+8x^2+4x-4,problem_4071
218,False,29x^5(2 - 7x^6),Solve this math problem step by step. You MUST...,Level 3,Algebra,-29x^5(7x^6-2),problem_49
230,False,436,Solve this math problem step by step. You MUST...,Level 4,Number Theory,14,problem_5040
360,False,1305,Solve this math problem step by step. You MUST...,Level 4,Precalculus,1305^\circ,problem_6937
367,False,,Solve this math problem step by step. You MUST...,Level 4,Precalculus,12,problem_7031
46,False,8.24,Solve this math problem step by step. You MUST...,Level 5,Algebra,\approx 8.24 \text{ mph},problem_1556
62,False,\dfrac{193}{512} \text{ or approximately } 37.7\%,Solve this math problem step by step. You MUST...,Level 5,Counting & Probability,\dfrac{193}{512},problem_1818
63,False,\dfrac{193}{512} \text{ or approximately } 37.7\%,Solve this math problem step by step. You MUST...,Level 5,Counting & Probability,\dfrac{193}{512},problem_1818
64,False,\dfrac{193}{512} \text{ or approximately } 37.7\%,Solve this math problem step by step. You MUST...,Level 5,Counting & Probability,\dfrac{193}{512},problem_1818
169,False,,Solve this math problem step by step. You MUST...,Level 5,Intermediate Algebra,175,problem_3850
206,False,0,Solve this math problem step by step. You MUST...,Level 5,Intermediate Algebra,"0, 1, 2, 4",problem_4656

In [32]:
results_df.loc[results_df['type'] == "Geometry"].sort_values('level').drop_duplicates()

,is_correct,model_answer,full_cot,level,type,correct_answer,problem_id
100,True,20,Solve this math problem step by step. You MUST...,Level 1,Geometry,20,problem_2606
122,True,17,Solve this math problem step by step. You MUST...,Level 1,Geometry,17,problem_2900
132,True,0,Solve this math problem step by step. You MUST...,Level 1,Geometry,0,problem_3252
97,False,9,Solve this math problem step by step. You MUST...,Level 2,Geometry,36,problem_2536
102,True,\dfrac{\sqrt{3}}{2},Solve this math problem step by step. You MUST...,Level 2,Geometry,\frac{\sqrt{3}}{2},problem_2617
103,True,12,Solve this math problem step by step. You MUST...,Level 2,Geometry,12,problem_2629
104,True,78\pi,Solve this math problem step by step. You MUST...,Level 2,Geometry,78\pi,problem_2632
110,False,55,Solve this math problem step by step. You MUST...,Level 2,Geometry,55^\circ,problem_2718
116,True,30,Solve this math problem step by step. You MUST...,Level 2,Geometry,30,problem_2779
118,False,"256\,\pi\ \text{cubic feet}",Solve this math problem step by step. You MUST...,Level 2,Geometry,256\pi,problem_2808
119,True,32,Solve this math problem step by step. You MUST...,Level 2,Geometry,32,problem_2831
126,True,36\pi,Solve this math problem step by step. You MUST...,Level 2,Geometry,36\pi,problem_3014
130,True,\dfrac{4}{5},Solve this math problem step by step. You MUST...,Level 2,Geometry,\frac45,problem_3195
133,True,8,Solve this math problem step by step. You MUST...,Level 2,Geometry,8,problem_3297
137,True,157.5,Solve this math problem step by step. You MUST...,Level 2,Geometry,157.5,problem_3379
138,True,7.8,Solve this math problem step by step. You MUST...,Level 2,Geometry,7.8,problem_3380
95,False,96,Solve this math problem step by step. You MUST...,Level 3,Geometry,100,problem_2521
107,True,32 - 8\pi,Solve this math problem step by step. You MUST...,Level 3,Geometry,32 - 8\pi,problem_2664
111,False,10,Solve this math problem step by step. You MUST...,Level 3,Geometry,10\sqrt{3},problem_2721
120,True,-\dfrac{\sqrt{3}}{2},Solve this math problem step by step. You MUST...,Level 3,Geometry,-\frac{\sqrt{3}}{2},problem_2858
134,True,1,Solve this math problem step by step. You MUST...,Level 3,Geometry,1,problem_3306
99,True,\dfrac{28}{3},Solve this math problem step by step. You MUST...,Level 4,Geometry,\dfrac{28}{3},problem_2575
101,True,\dfrac{1}{3},Solve this math problem step by step. You MUST...,Level 4,Geometry,\frac{1}{3},problem_2610
114,True,12 - 6\sqrt{3},Solve this math problem step by step. You MUST...,Level 4,Geometry,12 - 6\sqrt{3},problem_2734
123,True,10\sqrt{2},Solve this math problem step by step. You MUST...,Level 4,Geometry,10\sqrt{2},problem_2916
131,True,5400,Solve this math problem step by step. You MUST...,Level 4,Geometry,5400,problem_3208
136,True,102,Solve this math problem step by step. You MUST...,Level 4,Geometry,102,problem_3356
98,True,4\sqrt{3},Solve this math problem step by step. You MUST...,Level 5,Geometry,4\sqrt{3},problem_2542
108,True,72,Solve this math problem step by step. You MUST...,Level 5,Geometry,72,problem_2696
115,True,942,Solve this math problem step by step. You MUST...,Level 5,Geometry,942,problem_2761
124,True,307,Solve this math problem step by step. You MUST...,Level 5,Geometry,307,problem_3009
125,True,405,Solve this math problem step by step. You MUST...,Level 5,Geometry,405,problem_3011
127,True,12,Solve this math problem step by step. You MUST...,Level 5,Geometry,12,problem_3110
129,True,8\sqrt{5},Solve this math problem step by step. You MUST...,Level 5,Geometry,8\sqrt{5},problem_3175
135,True,8\sqrt{13},Solve this math problem step by step. You MUST...,Level 5,Geometry,8\sqrt{13},problem_3318

In [22]:
results_df.iloc[51]['full_cot']

"Solve this math problem step by step. You MUST put your final answer in \\boxed{}. Problem: The coefficients of the polynomial\n\\[x^4 + bx^3 + cx^2 + dx + e = 0\\]are all integers.  Let $n$ be the exact number of integer roots of the polynomial, counting multiplicity.  For example, the polynomial $(x + 3)^2 (x^2 + 4x + 11) = 0$ has two integer roots counting multiplicity, because the root $-3$ is counted twice.\n\nEnter all possible values of $n,$ separated by commas. Solution: \n<think>\nOkay, so I have this problem where I need to find all possible values of n, which is the exact number of integer roots of a polynomial with integer coefficients. The polynomial is a quartic, meaning it's degree 4, and it looks like this:\n\n\\[x^4 + bx^3 + cx^2 + dx + e = 0\\]\n\nAll the coefficients b, c, d, e are integers. The question is about the number of integer roots, counting multiplicity, which is denoted by n. They gave an example where the polynomial \\((x + 3)^2 (x^2 + 4x + 11) = 0\\) has two integer roots because -3 is a root with multiplicity 2, and the other roots are from the quadratic which don't have integer roots. So, n in that case is 2.\n\nI need to figure out all possible values of n. So, n can be 0, 1, 2, 3, or 4, right? Because it's a quartic, the maximum number of roots, counting multiplicity, is 4. So, n can't be more than 4. But not all these values might be possible depending on the conditions given.\n\nFirst, let me recall that if a polynomial has integer coefficients, then any rational root, when expressed in lowest terms p/q, must have p dividing the constant term and q dividing the leading coefficient. In this case, the leading coefficient is 1 because the polynomial is monic (the coefficient of x^4 is 1). So, any rational root must be an integer that divides e. So, all rational roots are integers, which simplifies things because we don't have to worry about fractions or anything.\n\nSo, the polynomial can have integer roots or non-integer roots. The non-integer roots would come in conjugate pairs if they are irrational or complex, right? Because non-real roots of polynomials with real coefficients come in complex conjugate pairs, but since all coefficients here are integers, which are real, the same applies. Similarly, irrational roots, if the polynomial has integer coefficients, must come in conjugate pairs as well because of the conjugate root theorem. So, that means if there's an irrational root a + b√c, there's also a + b√c's conjugate, which is a - b√c.\n\nBut wait, hold on, that's only for quadratic extensions, right? So, actually, any irrational roots must come in pairs because the minimal polynomial would have degree 2, so they come in pairs. Similarly, complex roots come in pairs as well because of the complex conjugate theorem. So, that would mean that the number of non-integer roots must be even. So, the number of integer roots must be such that the remaining roots are even in number.\n\nSo, the total degree is 4. So, if n is the number of integer roots, counting multiplicity, then the remaining roots, which are non-integer, must be 4 - n, and this number must be even. Therefore, 4 - n must be even, which implies that n must be even as well. Because 4 is even, so even minus even is even, but if 4 - n is even, then n must be even. So, n can be 0, 2, or 4.\n\nWait, but hold on, n counts the number of integer roots, each root counted as many times as its multiplicity. So, for example, if a root is repeated, like (x + 3)^2, then n would count 2 for that root. So, in that case, n could be even, but is it possible to have n as 1 or 3?\n\nWait, let me think again. If n is 1, that would mean there is one integer root, and the other three roots are non-integer. But wait, non-integer roots must come in pairs, so if we have three non-integer roots, that's an odd number, which is not possible because non-integer roots come in pairs. Therefore, the number of non-integer roots must be even. Therefore, 4 - n must be even, so n must be even.\n\nSimilarly, if n is 3, then 4 - 3 is 1, which is odd, so that's not possible. Therefore, n cannot be 1 or 3. So, the possible values of n are 0, 2, or 4.\n\nBut wait, is that always the case? Let me consider some examples.\n\nFirst, n = 4: This would mean all four roots are integers. For example, (x - 1)^4 = x^4 - 4x^3 + 6x^2 - 4x + 1. So, all coefficients are integers, and all roots are integer, each with multiplicity 1. So, n = 4 is possible.\n\nn = 2: For example, the given polynomial in the problem is (x + 3)^2 (x^2 + 4x + 11). So, here, -3 is a root with multiplicity 2, and the quadratic x^2 + 4x + 11 has discriminant 16 - 44 = -28, so it doesn't have real roots, let alone integer ones. So, n = 2 is possible.\n\nn = 0: That would mean all roots are non-integer. For example, take the polynomial (x^2 + 1)(x^2 + 2) = x^4 + 3x^2 + 2. All roots are imaginary, so certainly non-integer. Therefore, n = 0 is possible.\n\nBut wait, can we have n = 1? Let me try to construct a polynomial where there is exactly one integer root, but since non-integer roots must come in pairs, that would mean 3 non-integer roots, which is impossible. So, n = 1 is impossible.\n\nSimilarly, n = 3 would mean 1 non-integer root, which is impossible for the same reason. So, n can only be 0, 2, or 4.\n\nWait, but hold on a second. What about if the polynomial has a repeated integer root? For example, (x - 1)^2 (x^2 + 1) = 0. Here, x = 1 is a root with multiplicity 2, and the other roots are i and -i, which are non-integer. So, in this case, n = 2, since the integer root is counted twice. So, that's consistent with n being 2.\n\nAnother example: (x - 1)^3 (x + 1) = 0. Here, x = 1 is a root with multiplicity 3, and x = -1 is a root with multiplicity 1. So, total integer roots counting multiplicity would be 4. So, n = 4 here.\n\nWait, but that's 4 integer roots, not 3. Because even though 1 is a triple root, it's still an integer root, and -1 is a single root. So, n = 4.\n\nWait, so if I have a polynomial with a root of multiplicity 3, that's still an integer root, so n would count that as 3. But in that case, the total degree is 4, so the remaining root must be 1, which would have multiplicity 1, but wait, that's not possible because 4 - 3 is 1, which is odd. So, that would require the remaining root to be non-integer, but 1 is integer. So, that's a contradiction. Therefore, such a polynomial cannot exist. So, the multiplicity can't be 3 because that would require an odd number of non-integer roots, which is impossible.\n\nWait, let me clarify. If I have a polynomial with integer coefficients, and suppose it has a root at x = k with multiplicity m, then the polynomial can be written as (x - k)^m * Q(x), where Q(x) is another polynomial with integer coefficients. The roots of Q(x) must either be integers or come in conjugate pairs. Therefore, if Q(x) has any integer roots, they can add to n. If Q(x) doesn't have integer roots, then all its roots are non-integer and come in pairs.\n\nTherefore, if n is the total number of integer roots, counting multiplicity, then the remaining roots, which are non-integer, must come in pairs. So, 4 - n must be even, as I thought earlier.\n\nTherefore, 4 - n is even, which implies that n is even. So, n can be 0, 2, or 4.\n\nBut let me try to construct a polynomial where n = 2, but with one root of multiplicity 2 and another root of multiplicity 1, but that would make n = 3, which is odd, which is not allowed because 4 - 3 = 1, which is odd. So, such a polynomial can't exist because the remaining root can't be non-integer, but it's an integer root, which would mean 4 - n = 1, which is impossible.\n\nTherefore, the only possible values of n are 0, 2, 4.\n\nWait, but what about n = 1? Let me try to think of a polynomial with exactly one integer root. For example, suppose we have (x - 1)(x^3 + ax^2 + bx + c) = 0, where the cubic has no integer roots. But wait, a cubic with integer coefficients must have at least one real root, but that root could be irrational or complex. But if all roots of the cubic are non-integer, then n = 1. But wait, the cubic could have one real root and two complex roots, which would come in a conjugate pair. So, the cubic could have one real root and two complex roots, but all non-integer. So, in that case, n = 1.\n\nWait, but is that possible? Because in that case, 4 - 1 = 3, which is odd. So, the number of non-integer roots is 3, which is odd, but non-integer roots must come in pairs. So, that's impossible. Therefore, such a polynomial cannot exist.\n\nSimilarly, if I try to have n = 3, then 4 - 3 = 1, which is odd, so again, impossible. So, n can't be 3.\n\nTherefore, the only possible n values are 0, 2, and 4.\n\nWait, but let me think again. Suppose the polynomial is (x - 1)(x - 2)(x^2 + 1). So, here, we have two integer roots, 1 and 2, each with multiplicity 1, and two non-integer roots from x^2 + 1. So, n = 2. That works.\n\nAnother example: (x - 1)^2 (x^2 + 2x + 3). Here, 1 is a root with multiplicity 2, and the quadratic has no real roots, so n = 2.\n\nAnother example: (x + 1)(x + 1)(x + 1)(x + 1) = (x + 1)^4. Here, n = 4 because all four roots are -1, each with multiplicity 1, so total n = 4.\n\nAnother example: (x^2 + 1)(x^2 + 2). Here, all roots are non-integer, so n = 0.\n\nSo, these examples all fit into n being 0, 2, or 4.\n\nWait, but can I have n = 1? Let me try to construct such a polynomial.\n\nSuppose we have (x - 1)(x^3 + x + 1). So, x - 1 is integer root, and the cubic x^3 + x + 1. Let me check if it has integer roots. By Rational Root Theorem, possible roots are x = 1 or x = -1. Testing x=1: 1 + 1 + 1 = 3 ≠ 0. Testing x=-1: -1 -1 +1 = -1 ≠ 0. So, the cubic has no integer roots. Therefore, this polynomial has exactly one integer root, n = 1.\n\nBut wait, the cubic has degree 3, so it must have at least one real root, which is non-integer, and the other two roots could be complex conjugates. So, in this case, the total number of non-integer roots is 3, which is odd, but non-integer roots must come in pairs if they are real or complex. So, having three non-integer roots is impossible because they have to come in pairs. So, such a polynomial can't exist.\n\nTherefore, n = 1 is impossible because it would require the remaining three roots to be non-integer, which can't happen since they must come in pairs. Similarly, n = 3 would require the remaining root to be non-integer, but since the total degree is 4, n = 3 would require 1 non-integer root, which is impossible because non-integer roots must come in pairs.\n\nTherefore, the only possible values of n are 0, 2, and 4.\n\nWait, but let me check if n = 3 is possible. Suppose I have a polynomial with three integer roots and one non-integer root. But non-integer roots must come in pairs, so 1 non-integer root is impossible. So, n = 3 is impossible.\n\nSimilarly, n = 1 is impossible because it would require 3 non-integer roots, which is odd, so can't happen.\n\nTherefore, the possible values of n are 0, 2, and 4.\n\nSo, to sum up, because non-integer roots must come in pairs (either as complex conjugates or irrational conjugates), the number of non-integer roots must be even. Therefore, the number of integer roots, counting multiplicity, must satisfy 4 - n is even, which implies n is even. Therefore, n can be 0, 2, or 4.\n\nI think that's the conclusion.\n\n**Final Answer**\nThe possible values of \\( n \\) are \\boxed{0}, \\boxed{2}, and \\boxed{4}.\n</think>\n\nGiven the polynomial \n\n\\[x^4 + bx^3 + cx^2 + dx + e = 0\\]\n\nwith integer coefficients, we need to determine the possible values of \\( n \\), the exact number of integer roots counting multiplicity.\n\n1. **Rational Root Theorem**: Any rational root, expressed in lowest terms \\( \\frac{p}{q} \\), must have \\( p \\) dividing the constant term and \\( q \\) dividing the leading coefficient. Since the leading coefficient is 1, any rational root must be an integer.\n\n2. **Non-integer Roots**: Non-integer roots of polynomials with integer coefficients must come in pairs (either as complex conjugates or irrational conjugates). This means the number of non-integer roots must be even.\n\n3. **Total Degree Consideration**: The polynomial is of degree 4, so the total number of roots (counting multiplicity) is 4. If \\( n \\) is the number of integer roots, the remaining roots must be non-integer and thus must form an even number.\n\n4. **Even Number of Non-integer Roots**: Since the number of non-integer roots is \\( 4 - n \\) and must be even, \\( 4 - n \\) must be even. Therefore, \\( n \\) must be even.\n\n5. **Possible Values of \\( n \\)**: The possible values of \\( n \\) are 0, 2, or 4 because these are the even numbers that satisfy the condition that \\( 4 - n \\) is even.\n\nThus, the possible values of \\( n \\) are \\(\\boxed{0}\\), \\(\\boxed{2}\\), and \\(\\boxed{4}\\)."

In [21]:
(3*7*2) +(3*5*2)+(3*5*2*2) + (3*2*2*2*2)

180

In [19]:
(3*7*2)*(3*5*2)*(3*5*2)*(3*2*2*2*2)

1814400

In [20]:
10*9*8*7*6*5*4*3*2

3628800

In [ ]:
# [5104, 6765, 7162, 1923, 2542, 4656, 3011, 3558, 489, 3009]

##

Chunk 0 (base solution) - multiple Rollout Accuracy

In [41]:
for folder in os.listdir(base_soln_dir):
    if 'chunk_0' in os.listdir(os.path.join(base_soln_dir, folder)):
        with open(os.path.join(base_soln_dir, folder, 'chunk_0', 'solutions.json'), 'r') as f:
            solutions = json.load(f)
        print(folder)
        sol_list = [sol['is_correct'] for sol in solutions if 'is_correct' in sol]
        print('Number of solutions:', len(sol_list))
        print(pd.Series(sol_list).value_counts(normalize=True))

problem_1923
Number of solutions: 75
True     0.933333
False    0.066667
Name: proportion, dtype: float64
problem_2542
Number of solutions: 75
True     0.973333
False    0.026667
Name: proportion, dtype: float64
problem_3009
Number of solutions: 0
Series([], Name: proportion, dtype: float64)
problem_3011
Number of solutions: 0
Series([], Name: proportion, dtype: float64)
problem_3558
Number of solutions: 0
Series([], Name: proportion, dtype: float64)
problem_4656
Number of solutions: 0
Series([], Name: proportion, dtype: float64)
problem_489
Number of solutions: 75
True     0.986667
False    0.013333
Name: proportion, dtype: float64
problem_5104
Number of solutions: 0
Series([], Name: proportion, dtype: float64)
problem_6765
Number of solutions: 0
Series([], Name: proportion, dtype: float64)
problem_7162
Number of solutions: 75
True    1.0
Name: proportion, dtype: float64

In [37]:
os.path.join(base_soln_dir,'p\\chunk_0')

'C:\\Users\\Preet Lodaya\\Thought_Anchors\\thought-anchors\\math_rollouts\\accounts\\pdlodaya-l7vcn0oxxgj\\deployments\\dmmz204v\\temperature_0.6_top_p_0.95\\correct_base_solution\\p\\chunk_0'

In [8]:
import os, json

with open("math_rollouts/accounts/pdlodaya-l7vcn0oxxgj/deployments/e2zlc2rg/temperature_0.6_top_p_0.95/correct_base_solution/problem_1923/chunks.json", 'r') as f:
    data = json.load(f)

In [ ]:
import pandas as pd
lengths = []
# for chunk in data['chunks']:
    lengths.append(bridge.to_tokens(chunk).shape[-1])
pd.Series(lengths).describe()

count    170.000000
mean      14.011765
std        7.812892
min        3.000000
25%        9.000000
50%       12.000000
75%       18.000000
max       51.000000
dtype: float64

In [13]:
bridge.to_tokens(data['solution_text']).shape

torch.Size([1, 2449])

In [ ]:
from sentence_transformers import SentenceTransformer
import numpy as np
import pandas as pd

from pathlib import Path
import json


from dotenv import load_dotenv

# PROJECT_ROOT = Path(__file__).resolve().parent[3]
# print(PROJECT_ROOT)

load_dotenv()

def load_json(path: Path):
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)

RESAMPLED_BASE_DIR = Path(r"C:\Users\Preet Lodaya\Thought_Anchors\thought-anchors\math_rollouts\deepseek-r1-distill-qwen-14b\temperature_0.6_top_p_0.95")
SIMILARITY_MODEL_NAME = "all-MiniLM-L6-v2"
_similarity_model_cache = {}

def get_similarity_model(model_name: str = SIMILARITY_MODEL_NAME):
    if model_name not in _similarity_model_cache:
        _similarity_model_cache[model_name] = SentenceTransformer(model_name)
    return _similarity_model_cache[model_name]

def cosine_similarity(vec_a, vec_b):
    denom = np.linalg.norm(vec_a) * np.linalg.norm(vec_b)
    return float(np.dot(vec_a, vec_b) / denom) if denom else None

def get_resampled_chunk_similarities(problem_id, chunk_idx, base_dir=RESAMPLED_BASE_DIR, model_name: str = SIMILARITY_MODEL_NAME, solution_type: str = "correct"):
    problem_name = str(problem_id)
    if not problem_name.startswith("problem_"):
        problem_name = f"problem_{problem_name}"

    solutions_path = Path(base_dir) / f"{solution_type}_base_solution" / problem_name / f"chunk_{chunk_idx}" / "solutions.json"
    if not solutions_path.exists():
        raise FileNotFoundError(f"No resampled solutions found at {solutions_path}")

    solutions = load_json(solutions_path)
    model = get_similarity_model(model_name)
    rows = []
    texts_to_embed = []
    pending_pairs = []
    removed_chunk = None

    for solution_idx, sol in enumerate(solutions):
        removed = sol.get("chunk_removed")
        resampled = sol.get("chunk_resampled")

        if removed_chunk is None and isinstance(removed, str):
            removed_chunk = removed

        row = {
            "solution_idx": solution_idx,
            "chunk_resampled": resampled,
            "is_correct": sol.get("is_correct"),
            "answer": sol.get("answer"),
            "similarity": None,
        }
        rows.append(row)

        if isinstance(removed, str) and isinstance(resampled, str):
            pending_pairs.append(solution_idx)
            # texts_to_embed.extend([f"Following statements is from a math solution :- {removed}", f"Following statements is from a math solution :- {resampled}"])
            texts_to_embed.extend([removed, resampled])
    if pending_pairs:
        embeddings = model.encode(texts_to_embed, convert_to_numpy=True)
        for pair_idx, solution_idx in enumerate(pending_pairs):
            removed_embedding = embeddings[2 * pair_idx]
            resampled_embedding = embeddings[2 * pair_idx + 1]
            rows[solution_idx]["similarity"] = cosine_similarity(removed_embedding, resampled_embedding)

    results_df = pd.DataFrame(rows)
    valid_similarities = results_df["similarity"].dropna().tolist()

    print("removed_chunk:")
    print(removed_chunk)

    summary = {
        "problem_id": problem_name,
        "chunk_idx": int(chunk_idx),
        "solutions_path": str(solutions_path),
        "num_resamples": len(rows),
        "num_valid_pairs": len(valid_similarities),
        "mean_similarity": float(np.mean(valid_similarities)) if valid_similarities else None,
        "min_similarity": float(np.min(valid_similarities)) if valid_similarities else None,
        "max_similarity": float(np.max(valid_similarities)) if valid_similarities else None,
    }
    return removed_chunk, results_df, summary

# removed_chunk, similarity_df, summary = get_resampled_chunk_similarities("problem_330", 33)
# summary

In [25]:
i = 0
similarity_df.sort_values('similarity')['chunk_resampled'].values[i]

'Now, the entire expression is 3*(Layer 9), so I need to compute that: Final result: 3*29524 = Let me calculate that.'

In [26]:
similarity_df.sort_values('similarity')['similarity'].values[i]

np.float64(0.7082080245018005)

In [45]:
removed_chunk, similarity_df, summary = get_resampled_chunk_similarities("problem_330", 72, solution_type="incorrect")
summary

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

removed_chunk:
Let me try to compute each level again carefully.

{'problem_id': 'problem_330',
 'chunk_idx': 72,
 'solutions_path': 'C:\\Users\\Preet Lodaya\\Thought_Anchors\\thought-anchors\\math_rollouts\\deepseek-r1-distill-qwen-14b\\temperature_0.6_top_p_0.95\\incorrect_base_solution\\problem_330\\chunk_72\\solutions.json',
 'num_resamples': 100,
 'num_valid_pairs': 100,
 'mean_similarity': 0.7018475902080535,
 'min_similarity': 0.5355756878852844,
 'max_similarity': 0.9697916507720947}

In [46]:
# i = 0
for i in range(20):
    print(similarity_df.sort_values('similarity')['chunk_resampled'].values[i])

Let me try again, step by step, carefully: Level 1: (1 + 3) = 4 Level 2: 3*(1 + Level 1) = 3*(1 + 4) = 3*5 = 15 Level 3: 3*(1 + Level 2) = 3*(1 + 15) = 3*16 = 48 Level 4: 3*(1 + Level 3) = 3*(1 + 48) = 3*49 = 147 Level 5: 3*(1 + Level 4) = 3*(1 + 147) = 3*148 = 444 Level 6: 3*(1 + Level 5) = 3*(1 + 444) = 3*445 = 1335 Level 7: 3*(1 + Level 6) = 3*(1 + 1335) = 3*1336 = 4008 Level 8: 3*(1 + Level 7) = 3*(1 + 4008) = 3*4009 = 12027 Level 9: 3*(1 + Level 8) = 3*(1 + 12027) = 3*12028 = 36084 So, after 9 levels, the result is 36084.
Let me try again, perhaps I made an error in multiplication somewhere.
Let me try again, carefully, step by step, to ensure I don't make a mistake.
Let me try again, carefully, step by step, to make sure I don't make a mistake.
Let me check again step by step, perhaps I made an arithmetic error.
Let me try again, step by step, carefully, to ensure I don't make a mistake.
Let me double-check.
Let me check again, perhaps I messed up in the earlier steps.
Let me do it again carefully, step by step, to avoid mistakes.
Let me recount, step by step, carefully.
Let me try again more carefully.
Let me try again, more carefully.
Let me try again, more carefully.
Let me try again, more carefully.
Let me try again, more carefully.
Let me try again, more carefully.
Let me try this again more carefully.
Let me check again.
Let me check again.
Let me check again.

In [47]:
for i in range(20):
    print(similarity_df.sort_values('similarity')['similarity'].values[i])

0.5355756878852844
0.6340112090110779
0.6420028805732727
0.6449149250984192
0.644969642162323
0.6487084627151489
0.6540930271148682
0.6629245281219482
0.6637643575668335
0.6658450365066528
0.6667183041572571
0.6693230271339417
0.6693231463432312
0.6693231463432312
0.6693231463432312
0.6693231463432312
0.6731745600700378
0.674579918384552
0.6745800375938416
0.6745800375938416

In [48]:
# i = 0
for i in range(20):
    print(similarity_df.sort_values('similarity',ascending=False)['chunk_resampled'].values[i])

Let me try to compute each level correctly, step by step.
Let me try to compute each level again step by step, carefully, to avoid errors.
Let me try to compute each level step by step, carefully, to avoid mistakes.
Let me try again, carefully, step by step, ensuring each level is correct.
Let me try again, carefully, step by step, ensuring each level is correct.
Let me check again, perhaps I made a mistake in the number of levels.
Let me make a table to track each level properly.
Let me check each step again to be precise.
Let me check each step again carefully.
Let me check each step again carefully.
Let me check each step again carefully.
Let me check each step again carefully.
Let me check each step again carefully.
Let me check each step again carefully.
Let me check each step again carefully.
Let me double-check each step carefully.
Let me double-check each step carefully.
Let me double-check each step carefully.
Let me check each step carefully again.
Let me check each step carefully.