In [1]:
import json

In [2]:
with open("Results/deep_thinking_tokens_distances.json") as f:
    data = json.load(f)

In [4]:
data.keys()

dict_keys(['1591', '2050', '2137', '2189', '2236', '2238', '2870', '330', '3448', '3916', '4164', '4605', '4682', '6481', '6998'])

In [5]:
data['1591'].keys()

dict_keys(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100'])

In [7]:

pd.DataFrame(data['1591']['2'])

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.996094,1.000000,1.000000,...,0.972656,0.976562,0.972656,0.976562,0.972656,0.945312,0.917969,0.867188,0.921875,0.0
1,0.976562,0.980469,0.984375,0.980469,0.984375,0.984375,0.984375,0.984375,0.984375,0.984375,...,0.972656,0.972656,0.984375,0.976562,0.964844,0.957031,0.957031,0.957031,0.714844,0.0
2,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.972656,0.937500,0.953125,0.949219,0.964844,0.949219,0.945312,0.914062,0.443359,0.0
3,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.585938,0.507812,0.0
4,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.972656,0.232422,0.229492,0.0
5,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.984375,0.976562,0.976562,0.976562,0.972656,0.902344,0.789062,0.726562,0.482422,0.0
6,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.984375,0.984375,0.984375,0.988281,0.988281,0.976562,0.964844,0.964844,0.937500,0.0
7,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.992188,0.992188,0.988281,0.972656,0.796875,0.492188,0.162109,0.460938,0.0
8,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.996094,0.996094,0.996094,0.992188,0.996094,0.996094,0.800781,0.216797,0.0
9,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.996094,0.996094,0.996094,0.996094,1.000000,0.996094,0.937500,0.851562,0.0
10,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.984375,0.945312,0.957031,0.875000,0.867188,0.781250,0.621094,0.570312,0.742188,0.0
11,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.988281,0.988281,0.984375,0.976562,0.957031,0.929688,0.910156,0.828125,0.800781,0.0
12,0.996094,0.988281,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.980469,0.988281,0.988281,0.988281,0.984375,0.968750,0.960938,0.984375,0.988281,0.0
13,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.894531,0.917969,0.851562,0.785156,0.660156,0.087402,0.090820,0.153320,0.146484,0.0
14,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.500000,0.367188,0.214844,0.086914,0.000000,0.122070,0.076172,0.009705,0.013977,0.0
15,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.996094,0.996094,0.996094,0.996094,0.976562,0.949219,0.839844,0.910156,0.0
16,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.984375,0.984375,0.980469,0.980469,0.980469,0.964844,0.960938,0.964844,0.937500,0.0
17,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.617188,0.609375,0.067871,0.0
18,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.917969,0.953125,0.976562,0.984375,0.781250,0.769531,0.757812,0.281250,0.0
19,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.996094,0.996094,0.964844,0.890625,0.937500,0.298828,0.213867,0.083984,0.0
20,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.945312,0.945312,0.941406,0.957031,0.937500,0.941406,0.929688,0.878906,0.929688,0.0
21,0.988281,0.988281,0.988281,0.988281,0.988281,0.988281,0.988281,0.988281,0.988281,0.988281,...,0.976562,0.976562,0.972656,0.976562,0.964844,0.964844,0.960938,0.953125,0.648438,0.0

In [12]:
import pandas as pd
pd.DataFrame(data['1591']['25']).reset_index().rename(columns = {'index':'token'})#.insert(0, 'token', range(len(data['1591']['0']['0'])))

,token,0,1,2,3,4,5,6,7,8,...,22,23,24,25,26,27,28,29,30,31
0,0,0.988281,0.988281,0.988281,0.988281,0.988281,0.988281,0.988281,0.988281,0.988281,...,0.855469,0.882812,0.894531,0.890625,0.871094,0.742188,0.812500,0.738281,0.675781,0.0
1,1,0.984375,0.984375,0.984375,0.984375,0.988281,0.984375,0.984375,0.988281,0.988281,...,0.964844,0.976562,0.972656,0.941406,0.957031,0.949219,0.964844,0.945312,0.566406,0.0
2,2,0.992188,0.992188,0.992188,0.992188,0.992188,0.992188,0.992188,0.992188,0.992188,...,0.929688,0.929688,0.929688,0.925781,0.917969,0.843750,0.769531,0.679688,0.574219,0.0
3,3,0.988281,0.988281,0.988281,0.984375,0.988281,0.988281,0.992188,0.992188,0.992188,...,0.984375,0.984375,0.984375,0.984375,0.957031,0.886719,0.957031,0.683594,0.445312,0.0
4,4,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.984375,0.976562,0.976562,0.972656,0.968750,0.976562,0.960938,0.765625,0.664062,0.0
5,5,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.996094,0.996094,0.996094,0.996094,0.976562,0.902344,0.137695,0.128906,0.0
6,6,0.992188,0.992188,0.992188,0.992188,0.992188,0.992188,0.992188,0.992188,0.992188,...,0.964844,0.882812,0.992188,0.957031,0.937500,0.789062,0.628906,0.683594,0.554688,0.0
7,7,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.984375,0.976562,0.976562,0.988281,0.984375,0.964844,0.945312,0.882812,0.906250,0.0
8,8,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.988281,0.988281,0.988281,0.988281,0.984375,0.906250,0.800781,0.474609,0.753906,0.0
9,9,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.996094,0.996094,0.984375,0.964844,0.929688,0.988281,0.246094,0.085938,0.0
10,10,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.992188,0.898438,0.0
11,11,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.984375,0.960938,0.980469,0.937500,0.875000,0.851562,0.742188,0.761719,0.671875,0.0
12,12,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.968750,0.988281,0.976562,0.976562,0.964844,0.960938,0.937500,0.906250,0.832031,0.0
13,13,0.996094,0.992188,0.988281,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.988281,0.996094,0.996094,0.988281,0.988281,0.984375,0.937500,0.976562,0.984375,0.0
14,14,0.996094,0.996094,0.996094,0.996094,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.781250,0.851562,0.773438,0.730469,0.687500,0.112793,0.108398,0.123047,0.135742,0.0
15,15,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.376953,0.275391,0.158203,0.124512,0.000000,0.000000,0.012939,0.011292,0.010132,0.0
16,16,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.996094,0.988281,0.988281,0.988281,0.988281,0.984375,0.972656,0.843750,0.843750,0.0
17,17,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.984375,0.984375,0.976562,0.968750,0.964844,0.937500,0.949219,0.945312,0.855469,0.0
18,18,0.992188,0.992188,0.992188,0.992188,0.996094,0.996094,0.996094,0.992188,0.992188,...,0.960938,0.925781,0.917969,0.941406,0.945312,0.945312,0.902344,0.878906,0.369141,0.0
19,19,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.949219,0.945312,0.957031,0.886719,0.761719,0.789062,0.324219,0.146484,0.216797,0.0
20,20,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,0.996094,...,0.937500,0.917969,0.929688,0.957031,0.937500,0.941406,0.902344,0.851562,0.882812,0.0
21,21,0.980469,0.980469,0.984375,0.980469,0.980469,0.980469,0.980469,0.980469,0.980469,...,0.968750,0.976562,0.964844,0.984375,0.976562,0.964844,0.960938,0.960938,0.777344,0.0

In [16]:
result_df = pd.concat([
    pd.DataFrame(array).assign(problem_id=problem_id, chunk_id=chunk_id).reset_index().rename(columns = {'index':'token_id'})
    for problem_id, chunks in data.items()
    for chunk_id, array in chunks.items()
], ignore_index=True)

In [17]:
result_df.shape

(48921, 35)

In [19]:
distance_threshold = 0.5
depth_threshold = 0.9
num_layers = 32

In [20]:
# Step 1: Pivot the dataframe - convert layer columns to rows
# Identify layer columns (numeric columns 0-31)
layer_cols = [str(i) for i in range(num_layers)]

result_df_melted = result_df.melt(
    id_vars=['problem_id', 'chunk_id', 'token_id'],
    value_vars=layer_cols,
    var_name='layer_num',
    value_name='distance'
)

# Create layer names: layer_1, layer_2, ..., layer_32
result_df_melted['layer'] = 'layer_' + (result_df_melted['layer_num'].astype(int) + 1).astype(str)
result_df_melted = result_df_melted.drop('layer_num', axis=1)

result_df_melted.head()

  problem_id chunk_id  token_id  distance    layer
0       1591        0         0  0.984375  layer_1
1       1591        0         1  0.945312  layer_1
2       1591        0         2  0.996094  layer_1
3       1591        0         3  0.996094  layer_1
4       1591        0         4  0.996094  layer_1

In [21]:
# Step 2: For each (problem, chunk, token), sort by layer and compute cumulative minimum
result_df_melted['layer_idx'] = result_df_melted['layer'].str.replace('layer_', '').astype(int)
result_df_melted = result_df_melted.sort_values(['problem_id', 'chunk_id', 'token_id', 'layer_idx'])

# Compute cumulative minimum distance for each token
result_df_melted['distance'] = result_df_melted.groupby(['problem_id', 'chunk_id', 'token_id'])['distance'].cummin()

result_df_melted.head(40)

        problem_id chunk_id  token_id  distance     layer  layer_idx
0             1591        0         0  0.984375   layer_1          1
48921         1591        0         0  0.984375   layer_2          2
97842         1591        0         0  0.984375   layer_3          3
146763        1591        0         0  0.984375   layer_4          4
195684        1591        0         0  0.984375   layer_5          5
244605        1591        0         0  0.984375   layer_6          6
293526        1591        0         0  0.984375   layer_7          7
342447        1591        0         0  0.984375   layer_8          8
391368        1591        0         0  0.984375   layer_9          9
440289        1591        0         0  0.984375  layer_10         10
489210        1591        0         0  0.984375  layer_11         11
538131        1591        0         0  0.984375  layer_12         12
587052        1591        0         0  0.984375  layer_13         13
635973        1591        0         0  0.984375  layer_14         14
684894        1591        0         0  0.984375  layer_15         15
733815        1591        0         0  0.984375  layer_16         16
782736        1591        0         0  0.984375  layer_17         17
831657        1591        0         0  0.984375  layer_18         18
880578        1591        0         0  0.976562  layer_19         19
929499        1591        0         0  0.972656  layer_20         20
978420        1591        0         0  0.972656  layer_21         21
1027341       1591        0         0  0.972656  layer_22         22
1076262       1591        0         0  0.964844  layer_23         23
1125183       1591        0         0  0.960938  layer_24         24
1174104       1591        0         0  0.957031  layer_25         25
1223025       1591        0         0  0.957031  layer_26         26
1271946       1591        0         0  0.949219  layer_27         27
1320867       1591        0         0  0.949219  layer_28         28
1369788       1591        0         0  0.867188  layer_29         29
1418709       1591        0         0  0.867188  layer_30         30
1467630       1591        0         0  0.453125  layer_31         31
1516551       1591        0         0  0.000000  layer_32         32
1             1591        0         1  0.945312   layer_1          1
48922         1591        0         1  0.945312   layer_2          2
97843         1591        0         1  0.945312   layer_3          3
146764        1591        0         1  0.945312   layer_4          4
195685        1591        0         1  0.945312   layer_5          5
244606        1591        0         1  0.945312   layer_6          6
293527        1591        0         1  0.945312   layer_7          7
342448        1591        0         1  0.945312   layer_8          8

In [22]:
# Step 3: For each (problem, chunk, token), find first layer where distance < threshold
# Then check if that layer index >= depth_threshold * num_layers

def get_is_dtt(group):
    """
    For a given token, find the first layer where distance < distance_threshold.
    If that layer index >= depth_threshold * num_layers, return 1, else 0.
    If no layer crosses the threshold, return 0.
    """
    below_threshold = group[group['distance'] < distance_threshold]
    if len(below_threshold) == 0:
        # No layer crosses threshold, so is_dtt = 0
        return 0
    else:
        # Get first layer that crosses threshold
        first_layer_idx = below_threshold.iloc[0]['layer_idx']
        threshold_layer = depth_threshold * num_layers
        return 1 if first_layer_idx >= threshold_layer else 0

# Group by problem, chunk, token and apply the function
is_dtt_df = result_df_melted.groupby(['problem_id', 'chunk_id', 'token_id']).apply(get_is_dtt).reset_index()
is_dtt_df.columns = ['problem_id', 'chunk_id', 'token_id', 'is_dtt']

is_dtt_df.head(20)

   problem_id chunk_id  token_id  is_dtt
0        1591        0         0       1
1        1591        0         1       1
2        1591        0         2       1
3        1591        0         3       0
4        1591        0         4       0
5        1591        0         5       1
6        1591        0         6       1
7        1591        0         7       1
8        1591        0         8       1
9        1591        0         9       1
10       1591        0        10       1
11       1591        0        11       1
12       1591        0        12       1
13       1591        1         0       1
14       1591        1         1       1
15       1591        1         2       0
16       1591        1         3       1
17       1591        1         4       1
18       1591        1         5       1
19       1591        1         6       1

In [ ]:
# Step 4: Load chunks_labeled and extract importance measures
# Assuming chunks_labeled is loaded from a JSON file
# with open("path/to/chunks_labeled.json") as f:
#     chunks_labeled = json.load(f)

# Extract the four importance measures and create a dataframe
importance_data = []
for chunk in chunks_labeled:
    importance_data.append({
        'chunk_id': chunk['chunk_idx'],
        'resampling_importance_accuracy': chunk['resampling_importance_accuracy'],
        'resampling_importance_kl': chunk['resampling_importance_kl'],
        'counterfactual_importance_accuracy': chunk['counterfactual_importance_accuracy'],
        'counterfactual_importance_kl': chunk['counterfactual_importance_kl']
    })

importance_df = pd.DataFrame(importance_data)
importance_df.head()

In [ ]:
# Step 5: Merge importance measures with is_dtt_df on problem_id and chunk_id
# Add problem_id to importance_df (assuming problem_id can be extracted from the data source or passed in)
# For now, assuming you'll set problem_id appropriately
# importance_df['problem_id'] = problem_id  # Set this based on your data source

# Merge on problem_id and chunk_id
result_merged = is_dtt_df.merge(
    importance_df,
    on=['chunk_id'],
    how='left'
)

result_merged.head()

In [24]:
is_dtt_df['is_dtt'].value_counts(dropna=False,normalize=True)

is_dtt
1    0.737475
0    0.262525
Name: proportion, dtype: float64